name: Old tests

on:
  push

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest]
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
          python-version: ${{ matrix.python-version }}

    - name: Install the library
      shell: bash
      run: pip install .

    - name: Install dependencies
      shell: bash
      run: pip install -r requirements_dev.txt

    - name: Print all libs
      shell: bash
      run: pip list

    - name: Run tests and show coverage on the command line
      run: coverage run --source=cantok --omit="*tests*" -m pytest --cache-clear --assert=plain && coverage report -m --fail-under=100

    - name: Upload reports to codecov
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      if: runner.os == 'Linux'
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        find . -iregex "codecov.*"
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}

    - name: Run tests and show the branch coverage on the command line
      run: coverage run --branch --source=cantok --omit="*tests*" -m pytest --cache-clear --assert=plain && coverage report -m --fail-under=100
